INSERT INTO department(id, name, department_id) VALUES(1, 'W01', null)
INSERT INTO department(id, name, department_id) VALUES(2, 'W02', null)
INSERT INTO department(id, name, department_id) VALUES(3, 'W03', null)
INSERT INTO department(id, name, department_id) VALUES(4, 'W04', null)
INSERT INTO department(id, name, department_id) VALUES(5, 'W05', null)
INSERT INTO department(id, name, department_id) VALUES(6, 'W06', null)
INSERT INTO department(id, name, department_id) VALUES(7, 'W07', null)
INSERT INTO department(id, name, department_id) VALUES(8, 'W08', null)
INSERT INTO department(id, name, department_id) VALUES(9, 'W09', null)
INSERT INTO department(id, name, department_id) VALUES(10, 'W10', null)
INSERT INTO department(id, name, department_id) VALUES(11, 'W11', null)
INSERT INTO department(id, name, department_id) VALUES(12, 'W12', null)


INSERT INTO field_of_study(id, name, department_id) VALUES (1, 'Informatyka', 8)
INSERT INTO field_of_study(id, name, department_id) VALUES (2, 'Informatyka w jez.ang', 8)
INSERT INTO field_of_study(id, name, department_id) VALUES (3, 'Zarządzanie', 8)